version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: lab7-db
    restart: always
    ports:
      - "3307:3306"              # 3306 зайнятий локально, тому використовуємо 3307
    environment:
      MYSQL_ROOT_PASSWORD: BezdogannySQL
      MYSQL_DATABASE: inventorydb
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 3s

  server:
    build: .
    container_name: lab7-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"              # Порт API сервера
      - "9229:9229"              # Порт дебагу Nodemon/Node
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: BezdogannySQL
      DB_NAME: inventorydb
    command: >
      /usr/src/app/node_modules/.bin/nodemon
      --inspect=0.0.0.0:9229
      main.js -- -h 0.0.0.0 -p 8000 --cache ./dir
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  dbdata:
